networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  qdrant:
    image: qdrant/qdrant:v1.8.2-unprivileged
    networks:
      - frontend
      - app
    ports:
      - '6333'
      - '6334'
    environment:
      - "QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}"
    volumes:
      - ./qdrant_storage:/qdrant/storage:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=6333"
